modLoader="javafml"
loaderVersion="[47,)"
license="Public Domain"

[[mods]]
modId="doz_in_maincraft"
version="1.0.0"
displayName="DOZ_in_Maincraft"
displayURL="https://mcreator.net"
credits="\u043F"
authors="apple man, MCreator"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.doz_in_maincraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration